data<-read.table("household_power_consumption.txt", header=T, sep=";", stringsAsFactors=F, na.strings="?")
data1<-subset(data, Date %in% c("1/2/2007", "2/2/2007"))
data2<-as.numeric(data1$Global_active_power)
time<-strptime(paste(data1$Date, data1$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot2.png", width=480, height=480)
plot(time, data2, type = "l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
